export const INDUSTRIES = [
  {
    key: "agriculture",
    slug: "agriculture",
    title: "Agriculture & Farming",
    label: "Smart Farming",
    description: "Leverage technology to improve crop yield, supply chain, and farm management systems.",
    features: ["IoT-based monitoring", "Crop analytics", "Supply chain tracking"],
    ctaLabel: "Explore Agriculture",
  },
  {
    key: "fintech",
    slug: "fintech",
    title: "Fintech",
    label: "Financial Technology",
    description: "Build secure and scalable financial solutions including payments, wallets, and banking systems.",
    features: ["Payment gateways", "Digital wallets", "Fraud detection"],
    ctaLabel: "Explore Fintech",
  },
  {
    key: "healthcare",
    slug: "healthcare-fitness",
    title: "Healthcare & Fitness",
    label: "Medical Solutions",
    description: "Develop healthcare platforms with patient management, telemedicine, and fitness tracking.",
    features: ["Telemedicine", "Patient dashboards", "Health tracking"],
    ctaLabel: "Explore Healthcare",
  },
  {
    key: "education",
    slug: "education",
    title: "Education",
    label: "E-learning",
    description: "Interactive and scalable e-learning platforms with engaging content delivery systems.",
    features: ["LMS platforms", "Video learning", "Progress tracking"],
    ctaLabel: "Explore Education",
  },
  {
    key: "ecommerce",
    slug: "e-commerce",
    title: "E-Commerce",
    label: "Online Stores",
    description: "Build modern e-commerce platforms with seamless checkout and product management.",
    features: ["Cart & checkout", "Inventory management", "Payment integration"],
    ctaLabel: "Explore E-Commerce",
  },
  {
    key: "food-delivery",
    slug: "food-delivery",
    title: "Food Delivery",
    label: "On-demand Food",
    description: "Create food delivery apps with real-time tracking and order management systems.",
    features: ["Live tracking", "Order management", "Restaurant dashboards"],
    ctaLabel: "Explore Food Delivery",
  },
  {
    key: "logistics",
    slug: "logistic",
    title: "Logistics",
    label: "Supply Chain",
    description: "Optimize logistics operations with tracking, route optimization, and fleet management.",
    features: ["GPS tracking", "Fleet management", "Route optimization"],
    ctaLabel: "Explore Logistics",
  },
  {
    key: "real-estate",
    slug: "real-estate-marketplace",
    title: "Real Estate Marketplace",
    label: "Property Tech",
    description: "Develop real estate platforms with property listings, virtual tours, and CRM tools.",
    features: ["Property listings", "Virtual tours", "Agent CRM"],
    ctaLabel: "Explore Real Estate",
  },
  {
    key: "social-media",
    slug: "social-media",
    title: "Social Media",
    label: "Community Platforms",
    description: "Build scalable social media platforms with real-time interactions and engagement features.",
    features: ["Chat systems", "Feeds & posts", "Notifications"],
    ctaLabel: "Explore Social Media",
  },
];